# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auto Crawl And Push

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  schedule:
    - cron: '0 4 * * *'
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create file
      run: |
        # 定义一个数组，包含指定的城市名简写
        cities=("sz" "sh" "bj" "dg" "gz")  
        # 定义一个数组，包含所有的Python脚本
        scripts=("zufang.py" "loupan.py" "ershou.py" "xiaoqu.py") 
        # 遍历城市数组
        for city in "${cities[@]}"; do
            echo "Processing city: $city"
            # 遍历脚本数组，运行每个脚本
            for script in "${scripts[@]}"; do
                echo "Running script: $script for city:$city"
                python $script $city
            done
            echo "-----------------------------------"
        done

      # 配置git
    - name: Config git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github"
        git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"

    # 更新仓库
    - name: Update repo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls data -lh
        git add -f data
        git commit -m "auto update"
        git pull --rebase -X ours 
        git push -u origin
