# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "patch-sync-beike" ]
  pull_request:
    branches: [ "patch-sync-beike" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create file
      run: |
        #python loupan.py sz
        #python ershou.py sz
        #python xiaoqu.py sz
        python zufang.py sz

      # 配置git
    - name: Config git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github"
        git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"

    # 更新仓库
    - name: Update repo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add data/*
        git commit -m "auto update"
        git pull --rebase
        git push -u origin
